# Generated by Django 5.1.2 on 2024-10-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_remove_researcher_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='status',
        ),
        migrations.AlterField(
            model_name='researcher',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.researcher'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
